apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.warehouse.appName }}-configmap

data:
  APP_PORT: {{ .Values.warehouse.containerPort | quote }}
  ACTUATOR_PORT: {{ .Values.warehouse.actuatorPort | quote}}
  MAPPER_TYPE: "mapstruct"
  MEASURE_TRANSACTIONAL: "false"
  EXCHANGE_RATE_CLIENT_IMPLEMENTATION: "real"

  # cache setup
  REDIS_HOST: "{{ .Release.Name }}-{{ .Values.redis.appName }}"
  REDIS_PORT: {{ .Values.redis.containerPort | quote}}
  EXCHANGE_RATE_CLIENT_CACHE_EXPIRE: "1m"
  EXCHANGE_RATE_CLIENT_CACNE_NAME: "rates-redis-cache"

  # Scheduling setup
  SCHEDULING_ENABLED: "false"
  SCHEDULING_PERIOD: "60000"
  SCHEDULING_PRICE_PERCENT_INCREASE: "10.1"
  SCHEDULING_OPTIMIZATION_ENABLED: "true"
  SCHEDULING_USE_LOCK: "true"
  SCHEDULING_LOG_FILE_NAME: "scheduling-db-result.log"

  #INN service
  INN_SERVICE_HOST: "http://{{ .Release.Name }}-{{ .Values.innResolver.appName }}:{{ .Values.innResolver.containerPort }}"
  INN_SERVICE_INNS_ENDPOINT: "/api/v1/inns/resolve"
  INN_SERVICE_TIMEOUT_CONNECT_DURATION: "5s"
  INN_SERVICE_TIMEOUT_READ_DURATION: "5s"
  INN_SERVICE_READ_TIMEOUT_RETRY_ATTEMPTS: "10"
  INN_SERVICE_READ_TIMEOUT_RETRY_BACKOFF_DURATION: "2s"
  INN_SERVICE_SERVER_ERRORS_RETRY_ATTEMPTS: "1"
  INN_SERVICE_SERVER_ERRORS_RETRY_BACKOFF_DURATION: "5s"

  #ACCOUNT service
  ACCOUNT_SERVICE_HOST: "http://{{ .Release.Name }}-{{ .Values.accountNumberResolver.appName }}:{{ .Values.accountNumberResolver.containerPort }}"
  ACCOUNT_SERVICE_ACC_NUMBERS_ENDPOINT: "/api/v1/account-numbers/search-by-logins"
  ACCOUNT_SERVICE_TIMEOUT_CONNECT_DURATION: "5s"
  ACCOUNT_SERVICE_TIMEOUT_READ_DURATION: "5s"
  ACCOUNT_SERVICE_READ_TIMEOUT_RETRY_ATTEMPTS: "10"
  ACCOUNT_SERVICE_READ_TIMEOUT_RETRY_BACKOFF_DURATION: "2s"
  ACCOUNT_SERVICE_SERVER_ERRORS_RETRY_ATTEMPTS: "1"
  ACCOUNT_SERVICE_SERVER_ERRORS_RETRY_BACKOFF_DURATION: "5s"

  #EXCHANGE service
  EXCHANGE_SERVICE_HOST: "http://{{ .Release.Name }}-{{ .Values.exchangeService.appName }}:{{ .Values.exchangeService.containerPort }}"
  EXCHANGE_SERVICE_FALLBACK_FILE_NAME: "backupRates.json"
  EXCHANGE_SERVICE_CURRENCIES_ENDPOINT: "/api/v1/currencies"
  EXCHANGE_SERVICE_TIMEOUT_CONNECT_DURATION: "5s"
  EXCHANGE_SERVICE_TIMEOUT_READ_DURATION: "3s"
  EXCHANGE_SERVICE_READ_TIMEOUT_RETRY_ATTEMPTS: "10"
  EXCHANGE_SERVICE_READ_TIMEOUT_RETRY_BACKOFF_DURATION: "2s"
  EXCHANGE_SERVICE_SERVER_ERRORS_RETRY_ATTEMPTS: "1"
  EXCHANGE_SERVICE_SERVER_ERRORS_RETRY_BACKOFF_DURATION: "5s"



