spring:
  application:
    name: goods-warehouse
  profiles:
    default: dev
  liquibase:
    change-log: classpath:db/changelog/main-changelog.xml
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,caches,info
  endpoint:
    metrics:
      access: read_only
    caches:
      access: read_only
    health:
      access: read_only

logging:
  level:
    root: info
    #org.hibernate.SQL: DEBUG
    #org.hibernate.stat: DEBUG
    #org.hibernate.orm.jdbc.bind: TRACE

app:
  mapper:
    type: mapstruct # Choose between: conversion-service, mapstruct

  aspect:
    transactional:
      measure-execution-time: false # Highlighted because the aspect class lacks a @Value annotation for the property. ${} is used.

  scheduling:
    enabled: false
    period: 60000 # ms
    price-increase-percentage: 10.1
    optimization:
      enabled: false
      use-exclusive-lock: true
      output-file-name: scheduling-db-result.log

  exchange-rate-client:
    implementation: real

  cache:
    exchange-rate-client:
      expire-after-write: 1m
      record-stats: true

  rest:
    exchange-service:
      host: http://localhost:8088
      fallback-file: backupRates.json
      methods:
        currencies: /api/v1/currencies
      timeout:
        connect: 5s
        read: 3s
        retry:
          read-timeout:
            max-attempts: 10
            backoff: 2s
          server-errors:
            max-attempts: 1
            backoff: 5s