spring.application.name=goods-warehouse

spring.profiles.default=dev
spring.liquibase.change-log=classpath:db/changelog/main-changelog.xml

spring.jackson.property-naming-strategy=LOWER_CAMEL_CASE

# Pick mapper.
# Choose between: conversion-service, mapstruct
app.mapper.type=conversion-service