spring.application.name=goods-warehouse

spring.jackson.property-naming-strategy=LOWER_CAMEL_CASE
spring.profiles.default=dev

# Pick mapper.
# Choose between: conversion-service, mapstruct
app.mapper.type=conversion-service