apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-{{ .Values.db.appName }}
spec:
  serviceName: {{ .Release.Name }}-{{ .Values.db.appName}}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.db.appName | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.appName | quote }}
    spec:
      containers:
        - name: {{ .Values.db.containerName }}
          image: {{ .Values.db.image | quote }}
          ports:
            - containerPort: {{ .Values.db.containerPort }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db.name | quote }}

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-warehouse-secret
                  key: db-user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-warehouse-secret
                  key: db-password

          volumeMounts:
            - name: {{ .Values.db.storageName | quote }}
              mountPath: {{ .Values.db.mountPath | quote }}


          startupProbe:
            exec:
              command: [ "sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
            initialDelaySeconds: 15
            failureThreshold: 10
            periodSeconds: 10

          livenessProbe:
            exec:
              command: [ "sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 6

          readinessProbe:
            exec:
              command: [ "sh", "-c", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
            initialDelaySeconds: 0
            periodSeconds: 5
            failureThreshold: 3


  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.db.storageName | quote }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.db.storageSize | default "1Gi" | quote }}